# -*- coding: utf-8 -*-
"""DecisionTreeIbra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bMiasUCsUmmnr17njKc6f1nlBpX4Qz8Q
"""

#Mengimport Library Scikit Learn untuk Decision Tree, Dataset & Matplotlib 
from sklearn.tree import DecisionTreeClassifier 
from sklearn import datasets 
import matplotlib.pyplot as plt

#Load Dataset Iris dari Library sckit learn
iris = datasets.load_iris()
features = iris['data']
target = iris['target']
print(features)
len(features)

#Membuat Objek model decision tree 
decisiontree = DecisionTreeClassifier(random_state=0, max_depth=None,
                                      min_samples_split=2, min_samples_leaf=1,
                                      min_weight_fraction_leaf=0,
                                      max_leaf_nodes=None,
                                      min_impurity_decrease=0)

#Mentraining model Decision Tree
model = decisiontree.fit(features, target)

#mengambil sampel observasi dan membuat prediksi
#sampel berupa data dimensi kelopak
#fungsi predict() => memeriksa kelas yang dimilikinya 
#fungsi predict_proba() => memeriksa probabilitas kelas dari prediksi tersebut
observation = [[5,4,3,2]]
model.predict(observation)
model.predict_proba(observation)

#Membuat frafik visualisasi decison tree 
import pydotplus
from sklearn import tree
dot_data = tree.export_graphviz(decisiontree, out_file=None,
                                feature_names=iris['feature_names'],
                                class_names=iris['target_names'])
from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png('iris.png')